apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-docker-html-deployment
  labels:
    app: hello-docker-html
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-docker-html
  template:
    metadata:
      labels:
        app: hello-docker-html
    spec:
      containers:
      - name: hello-docker-html
        image: nginx:latest
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
        env:
        - name: KULLANICI
          value: Dunyali
        command: ["/bin/sh", "-c"]
        args:
        - sed -e s/Kullanici/"$KULLANICI"/ /usr/share/nginx/html/Hello_docker.html > /usr/share/nginx/html/index1.html && sed -e s/Hostname/"$(hostname)"/ /usr/share/nginx/html/index1.html > /usr/share/nginx/html/index.html && rm /usr/share/nginx/html/index1.html /usr/share/nginx/html/Hello_docker.html && exec nginx -g 'daemon off;'
